### ISSUE TITLE
widget引入的问题

### ISSUE THREAD

**Issue by Eva-Skye** [marsgis/mars3d-es5-project#1]
![de9b861129b76baf7e4d5c2b14519e5](https://user-images.githubusercontent.com/45868259/185579447-80f87c9e-ce39-4543-aa3e-76d5b8597a66.jpg)
![047f5333e01710a1f6aa75a39941470](https://user-images.githubusercontent.com/45868259/185580285-3d082785-2c35-44d4-858a-49311834ff60.jpg)

如图，从示例工程中copy出widget，在import的时候提示widget没有将方法导出，很是奇怪

**Comment by muyao1987** [comment]
需要再vite.config.js中添加如下配置
optimizeDeps: { include: ["widget.js 的路径"] },
